### ISSUE TITLE
ISO codes or Glottolog codes

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/norare-data#105]
all fine, if there's o iso-code, we should maybe think if we don't
switch to glottolog in general, would also be more consistent if more
data can be harvested?

_Originally posted by @LinguList in https://github.com/concepticon/norare-data/pull/104#issuecomment-655640242_

**Comment by xrotwang** [comment]
What I do when converting NoRaRe to CLDF:

1. Look up two or three-letter-code via `pycountry.languages`, then normalize to three-letter-code - i.e. ISO 639-3.
2. Map macrolanguages to the "closest standard language":
   ```python
   ISO_MAP = {
       'zho': 'cmn',
       'ara': 'arb',
       'msa': 'zsa',
       'fas': 'pes',
       'est': 'ekk',
       'swa': 'swh'}
   ```
3. Then lookup the ISO code to get Glottocodes.

**Comment by AnnikaTjuka** [comment]
That would make sense. We also use the three-letter-code to add the little flags in the language column at https://digling.org/norare/ when one looks up concepts:
<img width="1020" alt="Screenshot 2022-08-01 at 11 09 11" src="https://user-images.githubusercontent.com/45693807/182114776-b1da2257-e72f-49fd-9842-8642743baf81.png">

**Comment by xrotwang** [comment]
Using flags of countries as proxy for languages is sometimes frowned upon, so I'd rather not copy this feature over to the clld app.

**Comment by AnnikaTjuka** [comment]
> Using flags of countries as proxy for languages is sometimes frowned upon, so I'd rather not copy this feature over to the clld app.

I see. That's a good point.

**Comment by AnnikaTjuka** [comment]
@xrotwang @LinguList Can I close this issue?

**Comment by xrotwang** [comment]
I think so. The resolution now is
- keep ISO 639-1 or 639-3 codes in the raw data
- add Glottocodes in the CLDF data

**Comment by AnnikaTjuka** [comment]
Ok, good. That's how I understood the outcome of the discussion, too.
