### ISSUE TITLE
Data on Conceptual Specifity?

### ISSUE THREAD

**Issue by LinguList** [concepticon/norare-data#107]
Mariana Bolognesi will give a talk on [Two dimensions of conceptual representation: concreteness and specificity](https://www.conceptuccino-cms.uni-osnabrueck.de/index.php?id=1837), I do not know what the conclusions are, but wonder, if there is any rating data on specificity of concepts/words.

**Comment by AnnikaTjuka** [comment]
See: https://github.com/concepticon/norare-data/issues/189
