### ISSUE TITLE
Zhong et al. 2021: Sensorimotor Norms for Chinese Words

### ISSUE THREAD

**Issue by LinguList** [concepticon/norare-data#164]
https://doi.org/10.1080/23273798.2022.2035416

Data is on OSF: https://osf.io/t4zgu/

This is almost the same as in Lynott (also the plots), only in Chinese.

**Comment by AnnikaTjuka** [comment]
I've added the data to Concepticon recently: https://github.com/concepticon/concepticon-data/pull/1159

**Comment by LinguList** [comment]
Thanks a lot for spotting! Getting difficult to keep an overview at times.
