### ISSUE TITLE
DUTCH_PERCEPTUAL_STRENGTH_AGGREGATED defined as formula in source excel sheet

### ISSUE THREAD

**Issue by xrotwang** [concepticon/norare-data#185]
The variable `DUTCH_PERCEPTUAL_STRENGTH_AGGREGATED` in `Speed-2021-Sensorimotor` is extracted from the column `Minkowski3` in the source sheet. But this column is defined as formula `=SUM(B2^3, C2^3,D2^3,E2^3,F2^3,G2^3)^(1/3)`.

Saving the sheet as CSV would resolve this problem - and can probably be done programmatically.

**Comment by xrotwang** [comment]
```shell
$ libreoffice --headless --convert-to csv SpeedBrysbaert_Norms.xlsx --outdir /tmp/
```
does the right thing (but results in a CSV encoded in `cp1252`).

**Comment by AnnikaTjuka** [comment]
I think we would need to convert xlsx->csv in the `map.py` document so that the automatic mapping is based on the CSV file. Currently, we choose the function `get_excel` or `get_csv` depending on the raw data. Could we build in a workaround, @LinguList ?

**Comment by xrotwang** [comment]
I think adding
```python
subprocess.check_call('libreoffice --headless --convert-to csv SpeedBrysbaert_Norms.xlsx --outdir {}'.format(self.raw_dir).split())
```
after https://github.com/concepticon/norare-data/blob/7994f9615fe4f675dd24699744e560663563c00e/concept_set_meta/Speed-2021-Sensorimotor/map.py#L11 , and then calling `get_csv(...)` in `map` should do the trick.

**Comment by xrotwang** [comment]
Not sure excel does have something like "headless" mode - i.e. can be used without GUI easily. So I'd say we make `libreoffice` a requirement.

**Comment by AnnikaTjuka** [comment]
Great, thanks!
