### ISSUE TITLE
Release NoRaRe 1.0

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/norare-data#195]
As discussed in our Mattermost group chat, I added several issues to the milestone for [NoRaRe 1.0](https://github.com/concepticon/norare-data/milestone/1). I'm currently working through the issues and prioritizing the addition of new data sets. 

@LinguList There are some new data sets with the tag `ProduSemy`. Do we need to prioritize these to prepare for the start of your new project?

- [x] add data sets
- [x] release NoRaRe 1.0 as CLDF dataset (see https://github.com/concepticon/norare-cldf)
- [x] describe features for app
- [x] set up CLLD app

**Comment by LinguList** [comment]
No, the project has not even started, so there is time to do this later ;)

**Comment by xrotwang** [comment]
@AnnikaTjuka could we add the steps of the actual release process as items in this issue? (I already did that with one item)

**Comment by AnnikaTjuka** [comment]
@xrotwang Sure, I've started to add some steps, but I'll also go through the open issues again later.
